- name: nginx install and run
  hosts: frontend
  become: yes #for sudo access
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx server
    ansible.builtin.package:
      name: nginx
      state: started
      enable: yes     