- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print course informantion
    ansible.builtin.debug:
      msg: "hello {{ COURSE }} Course Duration: {{ DURATION }} Trainer is {{ TRAINER }}"