- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print course informantion
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, trainer is {{ TRAINER }}"