- name: functions
  hosts: local
  connection: local
  vars:
    persons: "vijay,tony,jayanth,subhash"
  tasks:
  - name: print undefined variable
    ansible.builtin.debug:
      msg: "Hello,{{ person | default('vijay')}}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello,{{ persons | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course Info: {{ course | dict2items  }}"        
