- name: functions
  hosts: local
  connection: local
  vars:
    "vijay,tony,jayanth,subhash"
  tasks:
  - name: print undefined variable
    ansible.builtin.debug:
      msg: "Hello,{{ person | default('vijay')}}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello,{{ person | split(',') }}"    
